import { createAction, createReducer, createSlice } from "@reduxjs/toolkit";

// task slice
const slice = createSlice({
  name: "cart",
  initialState: [],
  reducers: {
    addToCart: (state, action) => {
      state.push({
        id: action.payload.id,
        name:action.payload.name,
        description: action.payload.description,
      });
    },
    removeFromCart: (state, action) => {
      return state.filter((item) => item.id !== action.payload);
    },
  },
});

// Export the reducer to be used in the store
export default slice.reducer;

// Export the action creators generated by createSlice
export const { addToCart, removeFromCart } = slice.actions;

console.log(slice);
